EngChisl = dict()
EngChisl[1] = 'one'
EngChisl[2] = 'two'
EngChisl[3] = 'three'
EngChisl[4] = 'four'
EngChisl[5] = 'five'
EngChisl[6] = 'six'
EngChisl[7] = 'seven'
EngChisl[8] = 'eight'
EngChisl[9] = 'nine'
EngChisl[10] = 'ten'
EngChisl[11] = 'eleven'
EngChisl[12] = 'twelve'
EngChisl[14] = 'fourteen'
EngChisl['13-30'] = 'thir'
EngChisl['13-19_ok'] = 'teen'
EngChisl[15] = 'fif'
EngChisl[20] = 'twen'
EngChisl[40] = 'for'
EngChisl['20-90_ok'] = 'ty'
EngChisl[1000] = 'hundred'
x = 16
x = list(str(x))
x = EngChisl[int(x[1])] + EngChisl['13-19_ok']
print(x)
